AWSTemplateFormatVersion: '2010-09-09'
Description: Web Server Stack
Parameters:
  VPCStackName:
    Type: String
    Description: Name of the VPC stack to import resources from
  vpcid:
    Type: String
  subnetID1:
    Type: String
  subnetID2:
    Type: String
  DBPrivateIP:
    Type: String
  LSG:
    Type: String
  webSgroup:
    Type: String
  # intanceProfile:
  #   Type: String
Resources:
  MywebIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: nabeel-test-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
  webInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MywebIAMRole
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyLoadBalancer
      Scheme: internet-facing
      Subnets:
        - !Ref subnetID1
        - !Ref subnetID2
      SecurityGroups:
        - !Ref LSG
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: myTargetGroup
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !Ref vpcid
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-007855ac798b5175e
      InstanceType: t2.micro
      KeyName: my-key-pair
      AssociatePublicIpAddress: true   # Enable public IP for instances
      SecurityGroups:
        - !Ref webSgroup
      IamInstanceProfile: !Ref webInstanceProfile
      UserData: 
        Fn::Base64:
          !Sub 
            - |
              #!/bin/bash
              set -x
              sudo apt-get update -y
              sudo apt-get upgrade -y
              sudo apt install jq -y
              sudo apt install awscli -y
              sudo apt-get install apache2 -y
              sudo systemctl status apache2 -y
              sudo systemctl start apache2
              sudo systemctl enable apache2
              sudo apt-get install php php-mysql php-gd php-cli php-common -y
              sudo apt-get install wget unzip -y
              sudo wget https://wordpress.org/latest.zip
              sudo unzip latest.zip
              sudo cp -r wordpress/* /var/www/html/
              cd /var/www/html
              sudo chown www-data:www-data -R /var/www/html/
              sudo rm -rf index.html
              sudo cp wp-config-sample.php wp-config.php
              sudo sed -i "s/database_name_here/$(aws ssm get-parameter --region us-east-1 --name DBName --query 'Parameter.Value' --output text)/g" wp-config.php
              sudo sed -i "s/username_here/$(aws ssm get-parameter --region us-east-1 --name DBUser --query 'Parameter.Value' --output text)/g" wp-config.php
              sudo sed -i "s/password_here/$(aws ssm get-parameter --region us-east-1 --name DBPassword --query 'Parameter.Value' --output text)/g" wp-config.php
              sudo chown www-data:www-data wp-config.php
              sudo sed -i "s/localhost/${DatabaseIp}/g" wp-config.php
            - DatabaseIp: !Ref  DBPrivateIP
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: !Ref LaunchConfiguration
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      TargetGroupARNs:
        - !Ref TargetGroup
      VPCZoneIdentifier:
        - !Ref subnetID1
        - !Ref subnetID2
Outputs:
  LoadBalancerARN:
    Description: Load Balancer ARN
    Value: !Ref LoadBalancer
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerARN'
  TargetGroupARN:
    Description: Target Group ARN
    Value: !Ref TargetGroup
    Export:
      Name: !Sub '${AWS::StackName}-TargetGroupARN'


                   
              # with jq 
              # sudo sed -i "s/database_name_here/$(aws ssm get-parameter --region us-east-1 --name DBName --query 'Parameter.Value' --output text | jq -r '.')/g" wp-config.php
              # sudo sed -i "s/username_here/$(aws ssm get-parameter --region us-east-1 --name DBUser --query 'Parameter.Value' --output text | jq -r '.')/g" wp-config.php
              # sudo sed -i "s/password_here/$(aws ssm get-parameter --region us-east-1 --name DBPassword --query 'Parameter.Value' --output text | jq -r '.')/g" wp-config.php