AWSTemplateFormatVersion: '2010-09-09'
Description: DB Server Stack
Parameters:
  VPCStackName:
    Type: String
    Description: Name of the VPC stack to import resources from
  DBSecretARN:
    Type: String
    Description: ARN of the Secret in AWS Secrets Manager
  dbintance:
    Type: String
  PrivateID:
    Type: String
  vpcid:
    Type: String
Resources:
  DBServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-007855ac798b5175e   # Replace with AMI ID
      InstanceType: t2.micro   # Replace with instance type
      KeyName: my-key-pair   # Replace with the name of the EC2 key pair
      SubnetId: !Ref PrivateID  # Import the private subnet ID from the VPC stack
      Tags:
        - Key: Name
          Value: private-server-training
      SecurityGroupIds:
        - !Ref dbintance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x
          # Update and upgrade packages
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install jq -y
          sudo apt install awscli -y
          # Retrieve DB credentials from AWS Secrets Manager
          DBSecretValue=$(aws secretsmanager get-secret-value --secret-id ${DBSecretARN} --region us-east-1 --query 'SecretString' --output text)
          DBName=$(echo ${DBSecretValue} | jq -r '.dbname')
          DBUser=$(echo ${DBSecretValue} | jq -r '.username')
          DBPassword=$(echo ${DBSecretValue} | jq -r '.password')
          sudo apt install mysql-server -y
          sudo mysql -h localhost -u root <<EOF
          CREATE DATABASE $DBName;
          CREATE USER '$DBUser'@'%' IDENTIFIED BY '$DBPassword';
          GRANT ALL PRIVILEGES ON *.* TO '$DBUser'@'%';
          FLUSH PRIVILEGES;
          EOF
          sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo systemctl restart mysql
Outputs:
  DBInstancePrivateIP:
    Description: Private IP of the DB instance
    Value: !GetAtt DBServer.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-DBInstancePrivateIP'
